import { MoodKey } from './palettes';

export interface Painting {
  id: string;
  title: string;
  artist: string;
  year: string;
  moodProfile: Partial<Record<MoodKey, number>>;
}

export const PAINTINGS: Painting[] = [
  // ── Existing hand-curated paintings ──
  {
    id: 'scream',
    title: 'The Scream',
    artist: 'Edvard Munch',
    year: '1893',
    moodProfile: { red: 0.3, orange: 0.35, yellow: 0.1, darkBlue: 0.15, gray: 0.1 },
  },
  {
    id: 'impression-sunrise',
    title: 'Impression, Sunrise',
    artist: 'Claude Monet',
    year: '1872',
    moodProfile: { orange: 0.35, lightBlue: 0.25, darkBlue: 0.2, gray: 0.15, purple: 0.05 },
  },
  {
    id: 'sunflowers',
    title: 'Sunflowers',
    artist: 'Vincent van Gogh',
    year: '1888',
    moodProfile: { yellow: 0.5, orange: 0.2, green: 0.15, gray: 0.15 },
  },
  {
    id: 'the-kiss',
    title: 'The Kiss',
    artist: 'Gustav Klimt',
    year: '1908',
    moodProfile: { yellow: 0.3, pink: 0.25, purple: 0.15, green: 0.1, orange: 0.2 },
  },
  {
    id: 'the-dream',
    title: 'The Dream',
    artist: 'Henri Rousseau',
    year: '1910',
    moodProfile: { green: 0.4, purple: 0.2, orange: 0.15, pink: 0.15, black: 0.1 },
  },
  {
    id: 'great-wave',
    title: 'The Great Wave off Kanagawa',
    artist: 'Katsushika Hokusai',
    year: '1831',
    moodProfile: { lightBlue: 0.3, darkBlue: 0.35, yellow: 0.15, gray: 0.1, black: 0.1 },
  },
  {
    id: 'starry-night',
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: '1889',
    moodProfile: { darkBlue: 0.35, yellow: 0.2, purple: 0.2, lightBlue: 0.15, black: 0.1 },
  },
  {
    id: 'girl-pearl-earring',
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    year: '1665',
    moodProfile: { darkBlue: 0.3, yellow: 0.2, black: 0.25, lightBlue: 0.1, gray: 0.15 },
  },
  {
    id: 'composition-viii',
    title: 'Composition VIII',
    artist: 'Wassily Kandinsky',
    year: '1923',
    moodProfile: { purple: 0.2, red: 0.15, yellow: 0.2, lightBlue: 0.15, black: 0.15, orange: 0.15 },
  },
  {
    id: 'dance-bougival',
    title: 'Dance at Bougival',
    artist: 'Pierre-Auguste Renoir',
    year: '1883',
    moodProfile: { pink: 0.3, red: 0.25, yellow: 0.15, orange: 0.15, lightBlue: 0.15 },
  },
  {
    id: 'whistlers-mother',
    title: "Whistler's Mother",
    artist: 'James McNeill Whistler',
    year: '1871',
    moodProfile: { gray: 0.4, black: 0.4, darkBlue: 0.1, orange: 0.1 },
  },
  {
    id: 'night-watch',
    title: 'The Night Watch',
    artist: 'Rembrandt',
    year: '1642',
    moodProfile: { black: 0.35, orange: 0.25, yellow: 0.15, darkBlue: 0.15, red: 0.1 },
  },
  {
    id: 'wheatfield-cypresses',
    title: 'A Wheatfield with Cypresses',
    artist: 'Vincent van Gogh',
    year: '1889',
    moodProfile: { yellow: 0.3, green: 0.25, lightBlue: 0.25, darkBlue: 0.1, gray: 0.1 },
  },
  {
    id: 'birth-venus',
    title: 'The Birth of Venus',
    artist: 'Sandro Botticelli',
    year: '1486',
    moodProfile: { pink: 0.25, lightBlue: 0.25, green: 0.2, yellow: 0.15, orange: 0.15 },
  },
  {
    id: 'cafe-terrace',
    title: 'Café Terrace at Night',
    artist: 'Vincent van Gogh',
    year: '1888',
    moodProfile: { yellow: 0.35, darkBlue: 0.3, orange: 0.2, black: 0.1, lightBlue: 0.05 },
  },
  {
    id: 'persistence-memory',
    title: 'The Persistence of Memory',
    artist: 'Salvador Dalí',
    year: '1931',
    moodProfile: { yellow: 0.25, gray: 0.2, lightBlue: 0.2, orange: 0.15, darkBlue: 0.2 },
  },
  {
    id: 'red-vineyard',
    title: 'The Red Vineyard',
    artist: 'Vincent van Gogh',
    year: '1888',
    moodProfile: { red: 0.35, orange: 0.25, yellow: 0.2, purple: 0.1, darkBlue: 0.1 },
  },
  {
    id: 'blue-nude',
    title: 'Blue Nude II',
    artist: 'Henri Matisse',
    year: '1952',
    moodProfile: { darkBlue: 0.45, lightBlue: 0.3, gray: 0.15, black: 0.1 },
  },
  {
    id: 'girl-before-mirror',
    title: 'Girl before a Mirror',
    artist: 'Pablo Picasso',
    year: '1932',
    moodProfile: { pink: 0.3, purple: 0.25, yellow: 0.2, red: 0.15, gold: 0.1 },
  },
  {
    id: 'adele-bloch-bauer',
    title: 'Portrait of Adele Bloch-Bauer I',
    artist: 'Gustav Klimt',
    year: '1907',
    moodProfile: { gold: 0.45, yellow: 0.2, orange: 0.15, pink: 0.1, purple: 0.1 },
  },
  {
    id: 'wanderer-sea-fog',
    title: 'Wanderer above the Sea of Fog',
    artist: 'Caspar David Friedrich',
    year: '1818',
    moodProfile: { gray: 0.3, lightBlue: 0.2, darkBlue: 0.2, green: 0.15, gold: 0.15 },
  },

  // ── Art Institute of Chicago API — with IIIF image URLs ──
  {
    id: 'grande-jatte',
    title: 'A Sunday on La Grande Jatte — 1884',
    artist: 'Georges Seurat',
    year: '1886',
    moodProfile: { yellow: 0.3, lightBlue: 0.27, green: 0.16, pink: 0.1, darkBlue: 0.07, gray: 0.04, purple: 0.03, orange: 0.03 },
  },
  {
    id: 'paris-street-rainy',
    title: 'Paris Street; Rainy Day',
    artist: 'Gustave Caillebotte',
    year: '1877',
    moodProfile: { lightBlue: 0.35, darkBlue: 0.25, gray: 0.2, yellow: 0.1, pink: 0.1 },
  },
  {
    id: 'water-lilies-artic',
    title: 'Water Lilies',
    artist: 'Claude Monet',
    year: '1906',
    moodProfile: { lightBlue: 0.35, darkBlue: 0.25, green: 0.2, pink: 0.1, yellow: 0.1 },
  },
  {
    id: 'childs-bath',
    title: "The Child's Bath",
    artist: 'Mary Cassatt',
    year: '1893',
    moodProfile: { pink: 0.3, red: 0.2, yellow: 0.2, lightBlue: 0.15, gray: 0.15 },
  },
  {
    id: 'bedroom-van-gogh',
    title: 'The Bedroom',
    artist: 'Vincent van Gogh',
    year: '1889',
    moodProfile: { orange: 0.2, lightBlue: 0.2, yellow: 0.2, darkBlue: 0.15, red: 0.1, green: 0.1, purple: 0.05 },
  },
  {
    id: 'nighthawks',
    title: 'Nighthawks',
    artist: 'Edward Hopper',
    year: '1942',
    moodProfile: { darkBlue: 0.3, yellow: 0.25, green: 0.15, black: 0.15, gray: 0.15 },
  },
  {
    id: 'american-gothic',
    title: 'American Gothic',
    artist: 'Grant Wood',
    year: '1930',
    moodProfile: { gray: 0.3, orange: 0.25, darkBlue: 0.15, green: 0.15, black: 0.15 },
  },
  {
    id: 'two-sisters-terrace',
    title: 'Two Sisters (On the Terrace)',
    artist: 'Pierre-Auguste Renoir',
    year: '1881',
    moodProfile: { pink: 0.3, red: 0.2, lightBlue: 0.2, darkBlue: 0.15, yellow: 0.15 },
  },
  {
    id: 'self-portrait-van-gogh',
    title: 'Self-Portrait',
    artist: 'Vincent van Gogh',
    year: '1887',
    moodProfile: { lightBlue: 0.2, orange: 0.15, red: 0.15, darkBlue: 0.15, pink: 0.1, green: 0.1, yellow: 0.1, purple: 0.05 },
  },
  {
    id: 'mother-child-picasso',
    title: 'Mother and Child',
    artist: 'Pablo Picasso',
    year: '1921',
    moodProfile: { pink: 0.4, yellow: 0.25, lightBlue: 0.15, darkBlue: 0.1, gold: 0.1 },
  },
  {
    id: 'stacks-wheat',
    title: 'Stacks of Wheat (End of Summer)',
    artist: 'Claude Monet',
    year: '1891',
    moodProfile: { green: 0.35, yellow: 0.3, lightBlue: 0.2, orange: 0.1, gray: 0.05 },
  },
  {
    id: 'bay-marseilles',
    title: "The Bay of Marseille, Seen from L'Estaque",
    artist: 'Paul Cézanne',
    year: '1885',
    moodProfile: { lightBlue: 0.4, green: 0.2, yellow: 0.15, darkBlue: 0.15, orange: 0.1 },
  },
  {
    id: 'nightlife-motley',
    title: 'Nightlife',
    artist: 'Archibald John Motley Jr.',
    year: '1943',
    moodProfile: { red: 0.3, darkBlue: 0.3, black: 0.2, purple: 0.1, orange: 0.1 },
  },
  {
    id: 'flower-clouds',
    title: 'Flower Clouds',
    artist: 'Odilon Redon',
    year: '1903',
    moodProfile: { darkBlue: 0.3, lightBlue: 0.25, yellow: 0.25, purple: 0.1, pink: 0.1 },
  },
  {
    id: 'water-lily-pond',
    title: 'Water Lily Pond',
    artist: 'Claude Monet',
    year: '1900',
    moodProfile: { lightBlue: 0.3, yellow: 0.25, green: 0.2, darkBlue: 0.1, pink: 0.1, gray: 0.05 },
  },
  {
    id: 'greyed-rainbow',
    title: 'Greyed Rainbow',
    artist: 'Jackson Pollock',
    year: '1953',
    moodProfile: { yellow: 0.25, darkBlue: 0.2, lightBlue: 0.2, red: 0.15, black: 0.1, gray: 0.1 },
  },
  {
    id: 'rothko-purple-white-red',
    title: 'Untitled (Purple, White, and Red)',
    artist: 'Mark Rothko',
    year: '1953',
    moodProfile: { red: 0.45, purple: 0.25, pink: 0.15, gray: 0.15 },
  },
  {
    id: 'black-cross-okeeffe',
    title: 'Black Cross, New Mexico',
    artist: "Georgia O'Keeffe",
    year: '1929',
    moodProfile: { black: 0.3, orange: 0.25, green: 0.2, darkBlue: 0.15, purple: 0.1 },
  },
  {
    id: 'girl-by-window-munch',
    title: 'The Girl by the Window',
    artist: 'Edvard Munch',
    year: '1893',
    moodProfile: { darkBlue: 0.3, lightBlue: 0.25, yellow: 0.15, black: 0.15, pink: 0.1, purple: 0.05 },
  },
  {
    id: 'arrival-normandy-train',
    title: 'Arrival of the Normandy Train, Gare Saint-Lazare',
    artist: 'Claude Monet',
    year: '1877',
    moodProfile: { darkBlue: 0.25, gray: 0.2, red: 0.2, lightBlue: 0.15, green: 0.1, yellow: 0.1 },
  },

  // ── Bulk: Art Institute of Chicago public domain paintings ──
  {
    id: 'for-t-de-compi-gne',
    title: 'Forêt de Compiègne',
    artist: 'Berthe Morisot',
    year: '1885',
    moodProfile: { yellow: 0.31, lightBlue: 0.15, green: 0.46, teal: 0.08 },
  },
  {
    id: 'landscape-window-overlooking-the-woods',
    title: 'Landscape: Window Overlooking the Woods',
    artist: 'Édouard Jean Vuillard',
    year: '1899',
    moodProfile: { yellow: 0.34, lightBlue: 0.21, green: 0.28, pink: 0.1, orange: 0.03, gray: 0.03 },
  },
  {
    id: 'landscape-at-chailly',
    title: 'Landscape at Chailly',
    artist: 'Frédéric Bazille',
    year: '1865',
    moodProfile: { lightBlue: 0.57, yellow: 0.1, gray: 0.05, green: 0.29 },
  },
  {
    id: 'view-of-delphi-with-a-procession',
    title: 'View of Delphi with a Procession',
    artist: 'Claude Lorrain',
    year: '1673',
    moodProfile: { lightBlue: 0.38, gray: 0.1, green: 0.38, orange: 0.05, pink: 0.1 },
  },
  {
    id: 'wooded-landscape-with-cottage-and-horsem',
    title: 'Wooded Landscape with Cottage and Horseman',
    artist: 'Meindert Hobbema',
    year: '1663',
    moodProfile: { orange: 0.43, green: 0.43, teal: 0.14 },
  },
  {
    id: 'portrait-of-a-woman',
    title: 'Portrait of a Woman',
    artist: 'Amedeo Modigliani',
    year: 'c.1917/19',
    moodProfile: { orange: 0.3, pink: 0.25, gray: 0.2, darkBlue: 0.15, black: 0.1 },
  },
  {
    id: 'portrait-of-a-woman-with-a-black-fichu',
    title: 'Portrait of a Woman with a Black Fichu',
    artist: 'Édouard Manet',
    year: 'c.1878',
    moodProfile: { green: 0.53, pink: 0.12, gray: 0.12, lightBlue: 0.12, yellow: 0.12 },
  },
  {
    id: 'apples',
    title: 'Apples',
    artist: 'Henri Matisse',
    year: '1916',
    moodProfile: { orange: 0.73, yellow: 0.27 },
  },
  {
    id: 'trompe-l-oeil-still-life-with-a-flower-g',
    title: 'Trompe-l\'Oeil Still Life with a Flower Garland and a Curtain',
    artist: 'Adriaen van der Spelt',
    year: '1658',
    moodProfile: { lightBlue: 0.32, yellow: 0.32, orange: 0.21, pink: 0.16 },
  },
  {
    id: 'still-life-with-monkey-fruits-and-flower',
    title: 'Still Life with Monkey, Fruits, and Flowers',
    artist: 'Jean-Baptiste Oudry',
    year: '1724',
    moodProfile: { orange: 0.35, yellow: 0.18, green: 0.32, teal: 0.06, pink: 0.09 },
  },
  {
    id: 'fruit-piece',
    title: 'Fruit Piece',
    artist: 'Hannah Brown Skeele',
    year: '1860',
    moodProfile: { yellow: 0.67, orange: 0.33 },
  },
  {
    id: 'fish-still-life',
    title: 'Fish (Still Life)',
    artist: 'Édouard Manet',
    year: '1864',
    moodProfile: { yellow: 0.39, orange: 0.19, lightBlue: 0.06, red: 0.11, black: 0.25 },
  },
  {
    id: 'apples-and-grapes',
    title: 'Apples and Grapes',
    artist: 'Claude Monet',
    year: '1880',
    moodProfile: { yellow: 0.61, lightBlue: 0.09, orange: 0.3 },
  },
  {
    id: 'still-life-strawberries-nuts-c',
    title: 'Still Life—Strawberries, Nuts, &c.',
    artist: 'Raphaelle Peale',
    year: '1822',
    moodProfile: { orange: 0.65, yellow: 0.24, gray: 0.12 },
  },
  {
    id: 'magnolias-on-light-blue-velvet-cloth',
    title: 'Magnolias on Light Blue Velvet Cloth',
    artist: 'Martin Johnson Heade',
    year: '1885–95',
    moodProfile: { yellow: 0.56, orange: 0.11, green: 0.17, pink: 0.17 },
  },
  {
    id: 'seascape',
    title: 'Seascape',
    artist: 'Pierre-Auguste Renoir',
    year: '1879',
    moodProfile: { lightBlue: 0.55, yellow: 0.06, gray: 0.03, darkBlue: 0.16, green: 0.19 },
  },
  {
    id: 'the-departure-of-the-boats-tretat',
    title: 'The Departure of the Boats, Étretat',
    artist: 'Claude Monet',
    year: '1885',
    moodProfile: { yellow: 0.31, lightBlue: 0.42, darkBlue: 0.08, teal: 0.08, green: 0.12 },
  },
  {
    id: 'moonrise',
    title: 'Moonrise',
    artist: 'George Inness',
    year: '1891',
    moodProfile: { orange: 0.37, darkBlue: 0.25, black: 0.19, green: 0.19 },
  },
  {
    id: 'landscape-with-figures',
    title: 'Landscape with Figures',
    artist: 'Narcisse Virgile Diaz de la Peña',
    year: 'c.1870',
    moodProfile: { gray: 0.24, darkBlue: 0.32, black: 0.24, green: 0.12, pink: 0.08 },
  },
  {
    id: 'ad-astra',
    title: 'Ad Astra',
    artist: 'Akseli Gallen-Kallela',
    year: '1894–96',
    moodProfile: { orange: 0.33, darkBlue: 0.33, black: 0.17, lightBlue: 0.17 },
  },
  {
    id: 'the-eruption-of-vesuvius',
    title: 'The Eruption of Vesuvius',
    artist: 'Pierre-Jacques Volaire',
    year: '1771',
    moodProfile: { orange: 0.23, lightBlue: 0.12, darkBlue: 0.23, green: 0.23, teal: 0.08, black: 0.12 },
  },
  {
    id: 'the-girl-by-the-window',
    title: 'The Girl by the Window',
    artist: 'Edvard Munch',
    year: '1893',
    moodProfile: { lightBlue: 0.28, yellow: 0.17, darkBlue: 0.31, black: 0.17, pink: 0.08 },
  },
  {
    id: 'the-abduction-of-the-sabine-women',
    title: 'The Abduction of the Sabine Women',
    artist: 'Luca Giordano',
    year: 'c.1675',
    moodProfile: { orange: 0.27, darkBlue: 0.36, black: 0.27, pink: 0.09 },
  },
  {
    id: 'the-moon-at-night',
    title: 'The Moon at Night',
    artist: 'George Inness',
    year: '1890',
    moodProfile: { darkBlue: 0.35, yellow: 0.25, orange: 0.15, black: 0.15, gray: 0.1 },
  },
  {
    id: 'moulin-de-la-galette',
    title: 'Moulin de la Galette',
    artist: 'Henri de Toulouse-Lautrec',
    year: '1889',
    moodProfile: { orange: 0.11, darkBlue: 0.25, black: 0.17, lightBlue: 0.09, yellow: 0.08, pink: 0.15, red: 0.08, teal: 0.04, gray: 0.04 },
  },
  {
    id: 'nocturne-blue-and-gold-southampton-water',
    title: 'Nocturne: Blue and Gold—Southampton Water',
    artist: 'James McNeill Whistler',
    year: '1872',
    moodProfile: { orange: 0.2, green: 0.1, lightBlue: 0.3, yellow: 0.07, darkBlue: 0.2, gray: 0.03, black: 0.1 },
  },
  {
    id: 'icebound',
    title: 'Icebound',
    artist: 'John Henry Twachtman',
    year: 'c.1889',
    moodProfile: { teal: 0.18, green: 0.18, lightBlue: 0.39, yellow: 0.06, gray: 0.12, darkBlue: 0.06 },
  },
  {
    id: 'man-with-lance-riding-through-the-snow',
    title: 'Man with Lance Riding through the Snow',
    artist: 'Adolphe Schreyer',
    year: 'c.1880',
    moodProfile: { yellow: 0.24, lightBlue: 0.24, gray: 0.16, green: 0.16, orange: 0.12, gold: 0.08 },
  },
  {
    id: 'sandvika-norway',
    title: 'Sandvika, Norway',
    artist: 'Claude Monet',
    year: '1895',
    moodProfile: { teal: 0.24, lightBlue: 0.4, yellow: 0.08, green: 0.12, gray: 0.16 },
  },
  {
    id: 'winter-scene',
    title: 'Winter Scene',
    artist: 'Francisco José de Goya y Lucientes',
    year: 'c.1786',
    moodProfile: { gray: 0.45, green: 0.23, orange: 0.05, lightBlue: 0.27 },
  },
  {
    id: 'the-song-of-the-lark',
    title: 'The Song of the Lark',
    artist: 'Jules Breton',
    year: '1884',
    moodProfile: { orange: 0.3, yellow: 0.25, green: 0.2, gold: 0.15, pink: 0.1 },
  },
  {
    id: 'stack-of-wheat-thaw-sunset',
    title: 'Stack of Wheat (Thaw, Sunset)',
    artist: 'Claude Monet',
    year: '1890–91',
    moodProfile: { gray: 0.27, lightBlue: 0.23, yellow: 0.08, green: 0.35, teal: 0.08 },
  },
  {
    id: 'landscape-sunset',
    title: 'Landscape, Sunset',
    artist: 'George Inness',
    year: '1887–89',
    moodProfile: { orange: 0.35, yellow: 0.2, green: 0.15, darkBlue: 0.15, red: 0.15 },
  },
  {
    id: 'stacks-of-wheat-sunset-snow-effect',
    title: 'Stacks of Wheat (Sunset, Snow Effect)',
    artist: 'Claude Monet',
    year: '1890–91',
    moodProfile: { gray: 0.25, lightBlue: 0.29, yellow: 0.07, green: 0.21, teal: 0.07, darkBlue: 0.11 },
  },
  {
    id: 'cows-in-a-pond-at-sunset',
    title: 'Cows in a Pond at Sunset',
    artist: 'Sanford Robinson Gifford',
    year: '1860',
    moodProfile: { orange: 0.55, green: 0.27, lightBlue: 0.18 },
  },
  {
    id: 'merrymakers-in-an-inn',
    title: 'Merrymakers in an Inn',
    artist: 'Adriaen van Ostade',
    year: '1674',
    moodProfile: { orange: 0.3, yellow: 0.1, pink: 0.2, red: 0.1, purple: 0.3 },
  },
  {
    id: 'bacchic-revels',
    title: 'Bacchic Revels',
    artist: 'Johann Georg Platzer',
    year: 'c.1740',
    moodProfile: { gray: 0.14, pink: 0.14, purple: 0.14, green: 0.14, yellow: 0.14, teal: 0.1, orange: 0.07, lightBlue: 0.07, red: 0.05 },
  },
  {
    id: 'dorothea-and-francesca',
    title: 'Dorothea and Francesca',
    artist: 'Cecilia Beaux',
    year: '1898',
    moodProfile: { orange: 0.3, lightBlue: 0.1, yellow: 0.2, pink: 0.25, red: 0.1, gray: 0.05 },
  },
  {
    id: 'virgin-and-child-with-an-angel',
    title: 'Virgin and Child with an Angel',
    artist: 'Sandro Botticelli',
    year: '1475–85',
    moodProfile: { orange: 0.38, yellow: 0.25, pink: 0.13, purple: 0.13, gold: 0.13 },
  },
  {
    id: 'elizabeth-grant-bankson-beatty-mrs-james',
    title: 'Elizabeth Grant Bankson Beatty (Mrs. James Beatty) and Her Daughter Susan',
    artist: 'Joshua Johnson',
    year: 'c.1805',
    moodProfile: { orange: 0.55, yellow: 0.18, pink: 0.18, gray: 0.09 },
  },
  {
    id: 'love-of-winter',
    title: 'Love of Winter',
    artist: 'George Wesley Bellows',
    year: '1914',
    moodProfile: { orange: 0.2, green: 0.1, lightBlue: 0.3, yellow: 0.2, pink: 0.07, gray: 0.07, teal: 0.07 },
  },
  {
    id: 'yang-pu-moving-his-family',
    title: 'Yang Pu Moving His Family',
    artist: 'Unknown',
    year: '1279–1368',
    moodProfile: { lightBlue: 0.4, yellow: 0.1, pink: 0.05, green: 0.4, orange: 0.05 },
  },
  {
    id: 'the-poet-s-garden',
    title: 'The Poet\'s Garden',
    artist: 'Vincent van Gogh',
    year: '1888',
    moodProfile: { yellow: 0.34, lightBlue: 0.21, green: 0.31, pink: 0.1, gray: 0.03 },
  },
  {
    id: 'autumn-maples-with-poem-slips',
    title: 'Autumn Maples with Poem Slips',
    artist: 'Tosa Mitsuoki',
    year: 'c.1675',
    moodProfile: { red: 0.3, orange: 0.3, yellow: 0.2, gold: 0.15, green: 0.05 },
  },
  {
    id: 'october-day',
    title: 'October Day',
    artist: 'Jean Charles Cazin',
    year: '1890–93',
    moodProfile: { orange: 0.3, gray: 0.25, green: 0.2, yellow: 0.15, darkBlue: 0.1 },
  },
  {
    id: 'the-harvesters',
    title: 'The Harvesters',
    artist: 'Léon Augustin Lhermitte',
    year: '1888–89',
    moodProfile: { orange: 0.75, pink: 0.25 },
  },
  {
    id: 'stacks-of-wheat-end-of-day-autumn',
    title: 'Stacks of Wheat (End of Day, Autumn)',
    artist: 'Claude Monet',
    year: '1890–91',
    moodProfile: { red: 0.33, lightBlue: 0.33, yellow: 0.11, gray: 0.06, green: 0.17 },
  },
  {
    id: 'branch-of-the-seine-near-giverny-mist',
    title: 'Branch of the Seine near Giverny (Mist)',
    artist: 'Claude Monet',
    year: '1897',
    moodProfile: { darkBlue: 0.39, lightBlue: 0.39, yellow: 0.07, green: 0.11, gray: 0.04 },
  },
  {
    id: 'the-sacred-grove-beloved-of-the-arts-and',
    title: 'The Sacred Grove, Beloved of the Arts and the Muses',
    artist: 'Pierre Puvis de Chavannes',
    year: '1884–89',
    moodProfile: { yellow: 0.29, green: 0.26, lightBlue: 0.15, pink: 0.18, darkBlue: 0.06, teal: 0.06 },
  },
  {
    id: 'landscape',
    title: 'Landscape',
    artist: 'Théodore Rousseau',
    year: 'c.1835',
    moodProfile: { yellow: 0.22, lightBlue: 0.26, darkBlue: 0.07, gray: 0.04, green: 0.33, teal: 0.07 },
  },
  {
    id: 'the-bewitched-mill',
    title: 'The Bewitched Mill',
    artist: 'Franz Marc',
    year: '1913',
    moodProfile: { red: 0.35, green: 0.29, orange: 0.06, lightBlue: 0.18, darkBlue: 0.12 },
  },
  {
    id: 'landscape-with-two-poplars',
    title: 'Landscape with Two Poplars',
    artist: 'Vasily Kandinsky',
    year: '1912',
    moodProfile: { orange: 0.5, green: 0.5 },
  },
  {
    id: 'poppy-field-giverny',
    title: 'Poppy Field (Giverny)',
    artist: 'Claude Monet',
    year: '1890–91',
    moodProfile: { lightBlue: 0.41, yellow: 0.12, green: 0.26, pink: 0.09, darkBlue: 0.09, gray: 0.03 },
  },
  {
    id: 'hercules-and-the-lernaean-hydra',
    title: 'Hercules and the Lernaean Hydra',
    artist: 'Gustave Moreau',
    year: '1875–76',
    moodProfile: { orange: 0.32, black: 0.32, pink: 0.11, green: 0.16, lightBlue: 0.11 },
  },
  {
    id: 'french-street-scene',
    title: 'French Street Scene',
    artist: 'Edouard Béliard',
    year: '1873–77',
    moodProfile: { gray: 0.67, green: 0.33 },
  },
  {
    id: 'paris-street-rainy-day',
    title: 'Paris Street; Rainy Day',
    artist: 'Gustave Caillebotte',
    year: '1877',
    moodProfile: { lightBlue: 0.48, gray: 0.15, darkBlue: 0.09, yellow: 0.15, teal: 0.06, pink: 0.06 },
  },
  {
    id: 'the-assumption-of-the-virgin',
    title: 'The Assumption of the Virgin',
    artist: 'Domenico Theotokópoulos, called El Greco',
    year: '1577–79',
    moodProfile: { lightBlue: 0.38, black: 0.38, purple: 0.13, gold: 0.13 },
  },
  {
    id: 'the-ecstasy-of-saint-francis',
    title: 'The Ecstasy of Saint Francis',
    artist: 'Giovanni Baglione',
    year: '1601',
    moodProfile: { lightBlue: 0.6, purple: 0.2, gold: 0.2 },
  },
  {
    id: 'saint-francis-kneeling-in-meditation',
    title: 'Saint Francis Kneeling in Meditation',
    artist: 'Domenico Theotokópoulos, called El Greco',
    year: 'c.1595–c.160',
    moodProfile: { orange: 0.33, green: 0.33, purple: 0.11, gold: 0.11, teal: 0.11 },
  },
  {
    id: 'the-feast-in-the-house-of-simon',
    title: 'The Feast in the House of Simon',
    artist: 'El Greco (Doménikos Theotokópoulos) and workshop',
    year: 'c.1608–14',
    moodProfile: { orange: 0.6, purple: 0.2, gold: 0.2 },
  },
  {
    id: 'the-destruction-of-pharaoh-s-army',
    title: 'The Destruction of Pharaoh\'s Army',
    artist: 'Philippe Jacques de Loutherbourg, II',
    year: '1792',
    moodProfile: { orange: 0.4, purple: 0.13, gold: 0.13, lightBlue: 0.2, darkBlue: 0.13 },
  },
  {
    id: 'saint-john-the-baptist-entering-the-wild',
    title: 'Saint John the Baptist Entering the Wilderness',
    artist: 'Giovanni di Paolo',
    year: '1455–60',
    moodProfile: { orange: 0.4, green: 0.2, teal: 0.13, purple: 0.13, gold: 0.13 },
  },
  {
    id: 'battle-scene',
    title: 'Battle Scene',
    artist: 'Hippolyte Bellangé',
    year: 'c.1825',
    moodProfile: { orange: 0.32, red: 0.21, black: 0.47 },
  },
  {
    id: 'the-battle-of-zama',
    title: 'The Battle of Zama',
    artist: 'After Cornelis Cort',
    year: '1567',
    moodProfile: { red: 0.36, black: 0.32, green: 0.14, orange: 0.11, gold: 0.07 },
  },
  {
    id: 'the-combat-of-the-giaour-and-hassan',
    title: 'The Combat of the Giaour and Hassan',
    artist: 'Eugène Delacroix',
    year: '1826',
    moodProfile: { orange: 0.41, green: 0.18, red: 0.18, black: 0.14, gold: 0.09 },
  },
  {
    id: 'the-adventures-of-ulysses',
    title: 'The Adventures of Ulysses',
    artist: 'Apollonio di Giovanni',
    year: '1435–45',
    moodProfile: { orange: 0.25, darkBlue: 0.25, gold: 0.2, green: 0.15, red: 0.15 },
  },
  {
    id: 'interior-the-music-room-strandgade-30',
    title: 'Interior. The Music Room, Strandgade 30',
    artist: 'Vilhelm Hammershøi',
    year: '1907',
    moodProfile: { gray: 0.38, purple: 0.38, yellow: 0.13, orange: 0.13 },
  },

];
