import { MoodKey } from './palettes';

export interface Painting {
  id: string;
  title: string;
  titleZh: string;
  artist: string;
  artistZh: string;
  year: string;
  imageUrl: string | null;
  moodProfile: Partial<Record<MoodKey, number>>;
}

export const PAINTINGS: Painting[] = [
  // ── Existing hand-curated paintings ──
  {
    id: 'scream',
    title: 'The Scream',
    titleZh: '呐喊',
    artist: 'Edvard Munch',
    artistZh: '蒙克',
    year: '1893',
    imageUrl: null,
    moodProfile: { red: 0.3, orange: 0.35, yellow: 0.1, darkBlue: 0.15, gray: 0.1 },
  },
  {
    id: 'impression-sunrise',
    title: 'Impression, Sunrise',
    titleZh: '日出·印象',
    artist: 'Claude Monet',
    artistZh: '莫奈',
    year: '1872',
    imageUrl: null,
    moodProfile: { orange: 0.35, lightBlue: 0.25, darkBlue: 0.2, gray: 0.15, purple: 0.05 },
  },
  {
    id: 'sunflowers',
    title: 'Sunflowers',
    titleZh: '向日葵',
    artist: 'Vincent van Gogh',
    artistZh: '梵高',
    year: '1888',
    imageUrl: null,
    moodProfile: { yellow: 0.5, orange: 0.2, green: 0.15, gray: 0.15 },
  },
  {
    id: 'the-kiss',
    title: 'The Kiss',
    titleZh: '吻',
    artist: 'Gustav Klimt',
    artistZh: '克里姆特',
    year: '1908',
    imageUrl: null,
    moodProfile: { yellow: 0.3, pink: 0.25, purple: 0.15, green: 0.1, orange: 0.2 },
  },
  {
    id: 'the-dream',
    title: 'The Dream',
    titleZh: '梦',
    artist: 'Henri Rousseau',
    artistZh: '卢梭',
    year: '1910',
    imageUrl: null,
    moodProfile: { green: 0.4, purple: 0.2, orange: 0.15, pink: 0.15, black: 0.1 },
  },
  {
    id: 'great-wave',
    title: 'The Great Wave off Kanagawa',
    titleZh: '神奈川冲浪里',
    artist: 'Katsushika Hokusai',
    artistZh: '葛饰北斋',
    year: '1831',
    imageUrl: null,
    moodProfile: { lightBlue: 0.3, darkBlue: 0.35, yellow: 0.15, gray: 0.1, black: 0.1 },
  },
  {
    id: 'starry-night',
    title: 'The Starry Night',
    titleZh: '星月夜',
    artist: 'Vincent van Gogh',
    artistZh: '梵高',
    year: '1889',
    imageUrl: null,
    moodProfile: { darkBlue: 0.35, yellow: 0.2, purple: 0.2, lightBlue: 0.15, black: 0.1 },
  },
  {
    id: 'girl-pearl-earring',
    title: 'Girl with a Pearl Earring',
    titleZh: '戴珍珠耳环的少女',
    artist: 'Johannes Vermeer',
    artistZh: '维米尔',
    year: '1665',
    imageUrl: null,
    moodProfile: { darkBlue: 0.3, yellow: 0.2, black: 0.25, lightBlue: 0.1, gray: 0.15 },
  },
  {
    id: 'composition-viii',
    title: 'Composition VIII',
    titleZh: '构成第八号',
    artist: 'Wassily Kandinsky',
    artistZh: '康定斯基',
    year: '1923',
    imageUrl: null,
    moodProfile: { purple: 0.2, red: 0.15, yellow: 0.2, lightBlue: 0.15, black: 0.15, orange: 0.15 },
  },
  {
    id: 'dance-bougival',
    title: 'Dance at Bougival',
    titleZh: '布吉瓦尔的舞会',
    artist: 'Pierre-Auguste Renoir',
    artistZh: '雷诺阿',
    year: '1883',
    imageUrl: null,
    moodProfile: { pink: 0.3, red: 0.25, yellow: 0.15, orange: 0.15, lightBlue: 0.15 },
  },
  {
    id: 'whistlers-mother',
    title: "Whistler's Mother",
    titleZh: '灰与黑的协奏曲',
    artist: 'James McNeill Whistler',
    artistZh: '惠斯勒',
    year: '1871',
    imageUrl: null,
    moodProfile: { gray: 0.4, black: 0.4, darkBlue: 0.1, orange: 0.1 },
  },
  {
    id: 'night-watch',
    title: 'The Night Watch',
    titleZh: '夜巡',
    artist: 'Rembrandt',
    artistZh: '伦勃朗',
    year: '1642',
    imageUrl: null,
    moodProfile: { black: 0.35, orange: 0.25, yellow: 0.15, darkBlue: 0.15, red: 0.1 },
  },
  {
    id: 'wheatfield-cypresses',
    title: 'A Wheatfield with Cypresses',
    titleZh: '有丝柏的麦田',
    artist: 'Vincent van Gogh',
    artistZh: '梵高',
    year: '1889',
    imageUrl: null,
    moodProfile: { yellow: 0.3, green: 0.25, lightBlue: 0.25, darkBlue: 0.1, gray: 0.1 },
  },
  {
    id: 'birth-venus',
    title: 'The Birth of Venus',
    titleZh: '维纳斯的诞生',
    artist: 'Sandro Botticelli',
    artistZh: '波提切利',
    year: '1486',
    imageUrl: null,
    moodProfile: { pink: 0.25, lightBlue: 0.25, green: 0.2, yellow: 0.15, orange: 0.15 },
  },
  {
    id: 'cafe-terrace',
    title: 'Café Terrace at Night',
    titleZh: '夜间的露天咖啡座',
    artist: 'Vincent van Gogh',
    artistZh: '梵高',
    year: '1888',
    imageUrl: null,
    moodProfile: { yellow: 0.35, darkBlue: 0.3, orange: 0.2, black: 0.1, lightBlue: 0.05 },
  },
  {
    id: 'persistence-memory',
    title: 'The Persistence of Memory',
    titleZh: '记忆的永恒',
    artist: 'Salvador Dalí',
    artistZh: '达利',
    year: '1931',
    imageUrl: null,
    moodProfile: { yellow: 0.25, gray: 0.2, lightBlue: 0.2, orange: 0.15, darkBlue: 0.2 },
  },
  {
    id: 'red-vineyard',
    title: 'The Red Vineyard',
    titleZh: '红色葡萄园',
    artist: 'Vincent van Gogh',
    artistZh: '梵高',
    year: '1888',
    imageUrl: null,
    moodProfile: { red: 0.35, orange: 0.25, yellow: 0.2, purple: 0.1, darkBlue: 0.1 },
  },
  {
    id: 'blue-nude',
    title: 'Blue Nude II',
    titleZh: '蓝色裸体II',
    artist: 'Henri Matisse',
    artistZh: '马蒂斯',
    year: '1952',
    imageUrl: null,
    moodProfile: { darkBlue: 0.45, lightBlue: 0.3, gray: 0.15, black: 0.1 },
  },
  {
    id: 'girl-before-mirror',
    title: 'Girl before a Mirror',
    titleZh: '镜前少女',
    artist: 'Pablo Picasso',
    artistZh: '毕加索',
    year: '1932',
    imageUrl: null,
    moodProfile: { pink: 0.3, purple: 0.25, yellow: 0.2, red: 0.15, gold: 0.1 },
  },
  {
    id: 'adele-bloch-bauer',
    title: 'Portrait of Adele Bloch-Bauer I',
    titleZh: '阿黛尔·布洛赫-鲍尔I',
    artist: 'Gustav Klimt',
    artistZh: '克里姆特',
    year: '1907',
    imageUrl: null,
    moodProfile: { gold: 0.45, yellow: 0.2, orange: 0.15, pink: 0.1, purple: 0.1 },
  },
  {
    id: 'wanderer-sea-fog',
    title: 'Wanderer above the Sea of Fog',
    titleZh: '雾海上的漫游者',
    artist: 'Caspar David Friedrich',
    artistZh: '弗里德里希',
    year: '1818',
    imageUrl: null,
    moodProfile: { gray: 0.3, lightBlue: 0.2, darkBlue: 0.2, green: 0.15, gold: 0.15 },
  },

  // ── Art Institute of Chicago API — with IIIF image URLs ──
  {
    id: 'grande-jatte',
    title: 'A Sunday on La Grande Jatte — 1884',
    titleZh: '大碗岛的星期天下午',
    artist: 'Georges Seurat',
    artistZh: '修拉',
    year: '1886',
    imageUrl: 'https://www.artic.edu/iiif/2/2d484387-2509-5e8e-2c43-22f9981972eb/full/400,/0/default.jpg',
    moodProfile: { yellow: 0.3, lightBlue: 0.27, green: 0.16, pink: 0.1, darkBlue: 0.07, gray: 0.04, purple: 0.03, orange: 0.03 },
  },
  {
    id: 'paris-street-rainy',
    title: 'Paris Street; Rainy Day',
    titleZh: '巴黎街道·雨天',
    artist: 'Gustave Caillebotte',
    artistZh: '卡耶博特',
    year: '1877',
    imageUrl: 'https://www.artic.edu/iiif/2/f8fd76e9-c396-5678-36ed-6a348c904d27/full/400,/0/default.jpg',
    moodProfile: { lightBlue: 0.35, darkBlue: 0.25, gray: 0.2, yellow: 0.1, pink: 0.1 },
  },
  {
    id: 'water-lilies-artic',
    title: 'Water Lilies',
    titleZh: '睡莲',
    artist: 'Claude Monet',
    artistZh: '莫奈',
    year: '1906',
    imageUrl: 'https://www.artic.edu/iiif/2/3c27b499-af56-f0d5-93b5-a7f2f1ad5813/full/400,/0/default.jpg',
    moodProfile: { lightBlue: 0.35, darkBlue: 0.25, green: 0.2, pink: 0.1, yellow: 0.1 },
  },
  {
    id: 'childs-bath',
    title: "The Child's Bath",
    titleZh: '孩子的沐浴',
    artist: 'Mary Cassatt',
    artistZh: '卡萨特',
    year: '1893',
    imageUrl: 'https://www.artic.edu/iiif/2/3b885ae0-4d46-5fe4-d70a-00474827f02c/full/400,/0/default.jpg',
    moodProfile: { pink: 0.3, red: 0.2, yellow: 0.2, lightBlue: 0.15, gray: 0.15 },
  },
  {
    id: 'bedroom-van-gogh',
    title: 'The Bedroom',
    titleZh: '卧室',
    artist: 'Vincent van Gogh',
    artistZh: '梵高',
    year: '1889',
    imageUrl: 'https://www.artic.edu/iiif/2/6644829f-f292-c5c4-a73c-0356a6fdbf0d/full/400,/0/default.jpg',
    moodProfile: { orange: 0.2, lightBlue: 0.2, yellow: 0.2, darkBlue: 0.15, red: 0.1, green: 0.1, purple: 0.05 },
  },
  {
    id: 'nighthawks',
    title: 'Nighthawks',
    titleZh: '夜���',
    artist: 'Edward Hopper',
    artistZh: '霍珀',
    year: '1942',
    imageUrl: 'https://www.artic.edu/iiif/2/831a05de-d3f6-f4fa-a460-23008dd58dda/full/400,/0/default.jpg',
    moodProfile: { darkBlue: 0.3, yellow: 0.25, green: 0.15, black: 0.15, gray: 0.15 },
  },
  {
    id: 'american-gothic',
    title: 'American Gothic',
    titleZh: '美国哥特式',
    artist: 'Grant Wood',
    artistZh: '格兰特·伍德',
    year: '1930',
    imageUrl: 'https://www.artic.edu/iiif/2/b272df73-a965-ac37-4172-be4e99483637/full/400,/0/default.jpg',
    moodProfile: { gray: 0.3, orange: 0.25, darkBlue: 0.15, green: 0.15, black: 0.15 },
  },
  {
    id: 'two-sisters-terrace',
    title: 'Two Sisters (On the Terrace)',
    titleZh: '露台上的两姐妹',
    artist: 'Pierre-Auguste Renoir',
    artistZh: '雷诺阿',
    year: '1881',
    imageUrl: 'https://www.artic.edu/iiif/2/3a608f55-d76e-fa96-d0b1-0789fbc48f1e/full/400,/0/default.jpg',
    moodProfile: { pink: 0.3, red: 0.2, lightBlue: 0.2, darkBlue: 0.15, yellow: 0.15 },
  },
  {
    id: 'self-portrait-van-gogh',
    title: 'Self-Portrait',
    titleZh: '自画像',
    artist: 'Vincent van Gogh',
    artistZh: '梵高',
    year: '1887',
    imageUrl: 'https://www.artic.edu/iiif/2/47c5bcb8-62ef-e5d7-55e7-f5121f409a30/full/400,/0/default.jpg',
    moodProfile: { lightBlue: 0.2, orange: 0.15, red: 0.15, darkBlue: 0.15, pink: 0.1, green: 0.1, yellow: 0.1, purple: 0.05 },
  },
  {
    id: 'mother-child-picasso',
    title: 'Mother and Child',
    titleZh: '母与子',
    artist: 'Pablo Picasso',
    artistZh: '毕加索',
    year: '1921',
    imageUrl: 'https://www.artic.edu/iiif/2/64734461-887d-80b9-8489-e38cb05ac01d/full/400,/0/default.jpg',
    moodProfile: { pink: 0.4, yellow: 0.25, lightBlue: 0.15, darkBlue: 0.1, gold: 0.1 },
  },
  {
    id: 'stacks-wheat',
    title: 'Stacks of Wheat (End of Summer)',
    titleZh: '麦垛（夏末）',
    artist: 'Claude Monet',
    artistZh: '莫奈',
    year: '1891',
    imageUrl: 'https://www.artic.edu/iiif/2/a38e2828-ec6f-ece1-a30f-70243449197b/full/400,/0/default.jpg',
    moodProfile: { green: 0.35, yellow: 0.3, lightBlue: 0.2, orange: 0.1, gray: 0.05 },
  },
  {
    id: 'bay-marseilles',
    title: "The Bay of Marseille, Seen from L'Estaque",
    titleZh: '从莱斯塔克看马赛湾',
    artist: 'Paul Cézanne',
    artistZh: '塞尚',
    year: '1885',
    imageUrl: 'https://www.artic.edu/iiif/2/d4ca6321-8656-3d3f-a362-2ee297b2b813/full/400,/0/default.jpg',
    moodProfile: { lightBlue: 0.4, green: 0.2, yellow: 0.15, darkBlue: 0.15, orange: 0.1 },
  },
  {
    id: 'nightlife-motley',
    title: 'Nightlife',
    titleZh: '夜生活',
    artist: 'Archibald John Motley Jr.',
    artistZh: '莫特利',
    year: '1943',
    imageUrl: 'https://www.artic.edu/iiif/2/ec19d5f1-ae0f-5186-d421-4a53dca5fb90/full/400,/0/default.jpg',
    moodProfile: { red: 0.3, darkBlue: 0.3, black: 0.2, purple: 0.1, orange: 0.1 },
  },
  {
    id: 'flower-clouds',
    title: 'Flower Clouds',
    titleZh: '花云',
    artist: 'Odilon Redon',
    artistZh: '雷东',
    year: '1903',
    imageUrl: 'https://www.artic.edu/iiif/2/fb2077d9-82cc-ca7e-f450-5471d7f78c9a/full/400,/0/default.jpg',
    moodProfile: { darkBlue: 0.3, lightBlue: 0.25, yellow: 0.25, purple: 0.1, pink: 0.1 },
  },
  {
    id: 'water-lily-pond',
    title: 'Water Lily Pond',
    titleZh: '睡莲池',
    artist: 'Claude Monet',
    artistZh: '莫奈',
    year: '1900',
    imageUrl: 'https://www.artic.edu/iiif/2/8534685d-1102-e1e3-e194-94f6e925e8b0/full/400,/0/default.jpg',
    moodProfile: { lightBlue: 0.3, yellow: 0.25, green: 0.2, darkBlue: 0.1, pink: 0.1, gray: 0.05 },
  },
  {
    id: 'greyed-rainbow',
    title: 'Greyed Rainbow',
    titleZh: '灰色彩虹',
    artist: 'Jackson Pollock',
    artistZh: '波洛克',
    year: '1953',
    imageUrl: 'https://www.artic.edu/iiif/2/14dc5686-d7ae-7fe1-ec7d-adf14eb18b53/full/400,/0/default.jpg',
    moodProfile: { yellow: 0.25, darkBlue: 0.2, lightBlue: 0.2, red: 0.15, black: 0.1, gray: 0.1 },
  },
  {
    id: 'rothko-purple-white-red',
    title: 'Untitled (Purple, White, and Red)',
    titleZh: '无题（紫、白与红）',
    artist: 'Mark Rothko',
    artistZh: '罗斯科',
    year: '1953',
    imageUrl: 'https://www.artic.edu/iiif/2/4d152c81-8389-e426-e5f2-e98902d2515a/full/400,/0/default.jpg',
    moodProfile: { red: 0.45, purple: 0.25, pink: 0.15, gray: 0.15 },
  },
  {
    id: 'black-cross-okeeffe',
    title: 'Black Cross, New Mexico',
    titleZh: '黑色十字架·新墨西哥',
    artist: "Georgia O'Keeffe",
    artistZh: '欧姬芙',
    year: '1929',
    imageUrl: 'https://www.artic.edu/iiif/2/f98530b2-8570-58b2-38b4-e7544b49f1bd/full/400,/0/default.jpg',
    moodProfile: { black: 0.3, orange: 0.25, green: 0.2, darkBlue: 0.15, purple: 0.1 },
  },
  {
    id: 'girl-by-window-munch',
    title: 'The Girl by the Window',
    titleZh: '窗边的少女',
    artist: 'Edvard Munch',
    artistZh: '蒙克',
    year: '1893',
    imageUrl: 'https://www.artic.edu/iiif/2/d7df2633-3b40-f570-c906-211503a37cde/full/400,/0/default.jpg',
    moodProfile: { darkBlue: 0.3, lightBlue: 0.25, yellow: 0.15, black: 0.15, pink: 0.1, purple: 0.05 },
  },
  {
    id: 'arrival-normandy-train',
    title: 'Arrival of the Normandy Train, Gare Saint-Lazare',
    titleZh: '诺曼底列车抵达圣拉扎尔站',
    artist: 'Claude Monet',
    artistZh: '莫奈',
    year: '1877',
    imageUrl: 'https://www.artic.edu/iiif/2/0f1cc0e0-e42e-be16-3f71-2022da38cb93/full/400,/0/default.jpg',
    moodProfile: { darkBlue: 0.25, gray: 0.2, red: 0.2, lightBlue: 0.15, green: 0.1, yellow: 0.1 },
  },
];
